// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEeTJ933ZZiiOutB--mEofB27-dP8ij_8',
    appId: '1:519590058746:web:18def2d4e1dfc735104743',
    messagingSenderId: '519590058746',
    projectId: 'wordmania-8b3d6',
    authDomain: 'wordmania-8b3d6.firebaseapp.com',
    storageBucket: 'wordmania-8b3d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5d7MBd-VjzuiaFXs-Fbbyo0mPVqeDzk',
    appId: '1:519590058746:android:04f6817e6a45c894104743',
    messagingSenderId: '519590058746',
    projectId: 'wordmania-8b3d6',
    storageBucket: 'wordmania-8b3d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwEXaA-4a_wZOyFiC5Z1XYGbUxv1me5Ls',
    appId: '1:519590058746:ios:3465833decf03085104743',
    messagingSenderId: '519590058746',
    projectId: 'wordmania-8b3d6',
    storageBucket: 'wordmania-8b3d6.firebasestorage.app',
    iosBundleId: 'com.example.wordmania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwEXaA-4a_wZOyFiC5Z1XYGbUxv1me5Ls',
    appId: '1:519590058746:ios:3465833decf03085104743',
    messagingSenderId: '519590058746',
    projectId: 'wordmania-8b3d6',
    storageBucket: 'wordmania-8b3d6.firebasestorage.app',
    iosBundleId: 'com.example.wordmania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEeTJ933ZZiiOutB--mEofB27-dP8ij_8',
    appId: '1:519590058746:web:c95f6d71d39078f7104743',
    messagingSenderId: '519590058746',
    projectId: 'wordmania-8b3d6',
    authDomain: 'wordmania-8b3d6.firebaseapp.com',
    storageBucket: 'wordmania-8b3d6.firebasestorage.app',
  );
}
